<a href="https://colab.research.google.com/github/murigugitonga/math_4_ai/blob/dev/00_foundations/01_python_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Foundations — Python & NumPy for AI

**Author:** Murigu Gitonga  
**Objective:** Build numerical and array-based thinking using Python and NumPy,
which form the computational backbone of AI and ML systems.

---

> In AI, we do not think in loops — we think in vectors and matrices.


## 1. Why Python and NumPy?

- Python = orchestration language for AI
- NumPy = fast numerical computation
- ML frameworks (PyTorch, TensorFlow) are NumPy-like
- Understanding NumPy → understanding tensors later

Key mindset shift:
- Scalar → Vector → Matrix → Tensor


In [1]:
# Python scalar
x = 3
y = 4
x * y


12

In [2]:
import numpy as np

# NumPy array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a * b


array([ 4, 10, 18])

In [3]:
# Common ways to create vectors
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [4]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 2. Shape and Dimensionality

- shape → structure
- ndim → number of dimensions
- size → total number of elements


In [6]:
v = np.array([1, 2, 3])

v.shape, v.ndim, v.size


((3,), 1, 3)

In [7]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

M.shape, M.ndim, M.size


((2, 3), 2, 6)

## 3. Vectorization

Vectorization:
- Eliminates explicit loops
- Faster and more readable
- Critical for AI performance


In [8]:
# Loop-based (not recomm for ML)
result = []
for i in range(len(a)):
    result.append(a[i] * b[i])

result


[np.int64(4), np.int64(10), np.int64(18)]

In [9]:
# Vectorized
a * b


array([ 4, 10, 18])

## 4. Broadcasting

Broadcasting allows NumPy to operate on arrays of different shapes.


In [10]:
v = np.array([1, 2, 3])
v + 10


array([11, 12, 13])

In [11]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

M + v


array([[2, 4, 6],
       [5, 7, 9]])

In [12]:
x = np.array([1, 2, 3, 4, 5])

x.sum(), x.mean(), x.std()


(np.int64(15), np.float64(3.0), np.float64(1.4142135623730951))

In [13]:
M.sum(axis=0)  # column-wise


array([5, 7, 9])

In [14]:
M.sum(axis=1)  # row-wise


array([ 6, 15])

In [15]:
x = np.array([10, 20, 30, 40, 50])

x[0], x[-1]


(np.int64(10), np.int64(50))

In [16]:
x[1:4]


array([20, 30, 40])

In [17]:
M[0, :]


array([1, 2, 3])

In [18]:
M[:, 1]


array([2, 5])

## 5. Views vs Copies

This matters a LOT in ML pipelines.


In [19]:
a = np.array([1, 2, 3])
b = a

b[0] = 100
a


array([100,   2,   3])

In [20]:
np.random.seed(42)

np.random.randn(5)


array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

In [21]:
np.random.rand(3, 3)


array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

## 6. Key Takeaways

- NumPy arrays are the foundation of ML computation
- Vectorization replaces loops
- Broadcasting enables efficient math
- Shape awareness prevents bugs
